# Generated by Django 4.2.7 on 2025-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
