# Generated by Django 4.2.7 on 2025-02-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_f_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
