# Generated by Django 4.2.7 on 2025-02-09 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_profile_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 18, 33, 52, 302594)),
        ),
    ]
