# Generated by Django 4.2.7 on 2025-02-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_category_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
